In [1]:
import torch
import torch.nn as nn

In [24]:
class CNN(nn.Module):
    def __init__(self,num_classes):
        super(CNN,self).__init__()
        self.conv0 = nn.Sequential(
            nn.Conv2d(in_channels=3,out_channels=32,kernel_size=3,padding='same'),  # in_channels, out_channels, kernel_size
            nn.BatchNorm2d(32), 
            #nn.MaxPool2d(kernel_size=2,stride=2,padding = 'same'),  # kernel_size, stride
            nn.ReLU()            
        )
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=32,out_channels=32,kernel_size=3,padding='same'),  # in_channels, out_channels, kernel_size
            nn.BatchNorm2d(32), 
            #nn.MaxPool2d(kernel_size=2,stride=2,padding = 'same'),  # kernel_size, stride
            nn.ReLU()            
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(in_channels=32,out_channels=32,kernel_size=3,padding='same'),  # in_channels, out_channels, kernel_size
            nn.BatchNorm2d(32), 
            #nn.MaxPool2d(kernel_size=2,stride=2,padding = 'same'),  # kernel_size, stride
            nn.ReLU()            
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(in_channels=32,out_channels=32,kernel_size=3,padding='same'),  # in_channels, out_channels, kernel_size
            nn.BatchNorm2d(32), 
            #nn.MaxPool2d(kernel_size=2,stride=2,padding = 'same'),  # kernel_size, stride
            nn.ReLU()            
        )
        
        self.fc=nn.Sequential(
            #nn.Linear(in_features=7*7*64,out_features=2048),
            #nn.ReLU(),
            nn.Linear(in_features=225792,out_features=num_classes)
        )

    def forward(self,x):
        x = self.conv0(x)
        x = self.conv1(x)
        x = self.conv2(x)
        feature = (self.conv3(x))
        
        output=self.fc(feature.view(x.shape[0], -1))
        return output

In [25]:
net = CNN(2)

In [26]:
a = torch.rand(1,3, 84,84)

In [27]:
b = net(a)

In [28]:
print(b)

tensor([[-0.0217,  0.1278]], grad_fn=<AddmmBackward0>)


In [14]:
from resnet import ResNet18

In [15]:
import torchvision.models as models

In [16]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [17]:
print(torch.cuda.memory_allocated())

print(torch.cuda.memory_reserved())

244798464
257949696


In [18]:
x= torch.rand(2,2,device = device)

In [19]:
print(torch.cuda.memory_allocated())

print(torch.cuda.memory_reserved())

244798464
257949696


In [20]:
import copy
y=copy.deepcopy(x)

In [21]:
print(torch.cuda.memory_allocated())

print(torch.cuda.memory_reserved())

244798464
257949696


In [22]:
a = models.alexnet()
b = models.alexnet().to(device)

In [23]:
for name,par in b.named_children():
    print(name)
    print(par.training)

features
True
avgpool
True
classifier
True


In [24]:
from resnet_wDiscriminator_dropout import ResNet18_wDiscriminator_dropout

In [25]:
c =  ResNet18_wDiscriminator_dropout()

In [31]:
for name,par in c.named_children():
    print(name)
    print(par.training)
    
for name,par in c.named_parameters():
    print(name,par.requires_grad)

conv1
False
bn1
False
layer1
False
layer2
False
layer3
False
layer4
False
fc
False
discriminator
True
conv1.weight False
bn1.weight False
bn1.bias False
layer1.0.conv1.weight False
layer1.0.bn1.weight False
layer1.0.bn1.bias False
layer1.0.conv2.weight False
layer1.0.bn2.weight False
layer1.0.bn2.bias False
layer1.1.conv1.weight False
layer1.1.bn1.weight False
layer1.1.bn1.bias False
layer1.1.conv2.weight False
layer1.1.bn2.weight False
layer1.1.bn2.bias False
layer2.0.conv1.weight False
layer2.0.bn1.weight False
layer2.0.bn1.bias False
layer2.0.conv2.weight False
layer2.0.bn2.weight False
layer2.0.bn2.bias False
layer2.0.downsample.0.weight False
layer2.0.downsample.1.weight False
layer2.0.downsample.1.bias False
layer2.1.conv1.weight False
layer2.1.bn1.weight False
layer2.1.bn1.bias False
layer2.1.conv2.weight False
layer2.1.bn2.weight False
layer2.1.bn2.bias False
layer3.0.conv1.weight False
layer3.0.bn1.weight False
layer3.0.bn1.bias False
layer3.0.conv2.weight False
layer3.0.bn2.w

In [27]:
c.freezeDis_unfreezeElse()

In [30]:
c.unfreezeDis_freezeElse()

In [18]:
print(a.state_dict())

OrderedDict([('conv1.weight', tensor([[[[-0.1020,  0.0833, -0.0236],
          [ 0.1583,  0.1151,  0.0494],
          [-0.1144, -0.0944,  0.1241]],

         [[ 0.1868,  0.1447, -0.1717],
          [-0.1175,  0.1678,  0.0690],
          [ 0.1782, -0.0497, -0.0678]],

         [[ 0.1568, -0.0087,  0.0047],
          [-0.1875, -0.0249, -0.1174],
          [-0.1880, -0.1882, -0.1147]]],


        [[[ 0.1145, -0.0262, -0.1434],
          [-0.1698,  0.1284,  0.1600],
          [-0.0625, -0.1320, -0.1736]],

         [[-0.1394, -0.0963,  0.1631],
          [ 0.1017, -0.1372, -0.0944],
          [-0.1827, -0.0621, -0.0156]],

         [[ 0.0744, -0.0405, -0.1553],
          [-0.0609, -0.1404,  0.1201],
          [-0.1009,  0.0277,  0.0997]]],


        [[[-0.0308, -0.1262, -0.0467],
          [-0.0111, -0.1393, -0.0413],
          [-0.0466,  0.1571, -0.1526]],

         [[ 0.1148,  0.0390,  0.1139],
          [ 0.1307, -0.0573, -0.1025],
          [-0.1609, -0.0338, -0.0700]],

         [[-0.

In [19]:
print(b.state_dict())

OrderedDict([('conv1.weight', tensor([[[[ 0.1539, -0.0220,  0.1821],
          [-0.0776,  0.0133, -0.1252],
          [ 0.0945,  0.0564, -0.0568]],

         [[ 0.0414, -0.1170, -0.1390],
          [-0.1091, -0.1532, -0.0071],
          [ 0.1461, -0.1846,  0.1186]],

         [[ 0.1492, -0.0373, -0.0813],
          [-0.0125, -0.0113,  0.1697],
          [-0.1356, -0.0581, -0.0355]]],


        [[[-0.1640, -0.1760, -0.1291],
          [-0.0397, -0.0045,  0.0300],
          [ 0.0621, -0.0587, -0.0630]],

         [[ 0.0269,  0.0769, -0.1335],
          [ 0.0116, -0.1076, -0.1007],
          [ 0.1182,  0.1205,  0.0213]],

         [[ 0.0541,  0.0675, -0.1888],
          [ 0.0991,  0.0389,  0.0430],
          [ 0.0520,  0.0511, -0.0989]]],


        [[[-0.1164,  0.0607,  0.1441],
          [-0.1839,  0.0761, -0.1499],
          [ 0.1373, -0.1293, -0.0955]],

         [[-0.1717,  0.1372,  0.0987],
          [ 0.1227,  0.0141,  0.1743],
          [ 0.0168,  0.0879, -0.0761]],

         [[-0.

In [21]:
a.load_state_dict(b.state_dict())

<All keys matched successfully>

In [4]:
import torchvision.models as models
resnet18 = models.resnet18(pretrained=True)
myresnet18_withbnlayer = ResNet18(use_pretrained=True, transfer_learning = True,use_bn_layer = True)

note that conv1_kernel_size is : 7
Start synking model with pretrained

conv1.weight
synk

bn1.weight

bn1.bias

bn1.running_mean

bn1.running_var

bn1.num_batches_tracked

layer1.0.conv1.weight
synk

layer1.0.bn1.weight

layer1.0.bn1.bias

layer1.0.bn1.running_mean

layer1.0.bn1.running_var

layer1.0.bn1.num_batches_tracked

layer1.0.conv2.weight
synk

layer1.0.bn2.weight

layer1.0.bn2.bias

layer1.0.bn2.running_mean

layer1.0.bn2.running_var

layer1.0.bn2.num_batches_tracked

layer1.1.conv1.weight
synk

layer1.1.bn1.weight

layer1.1.bn1.bias

layer1.1.bn1.running_mean

layer1.1.bn1.running_var

layer1.1.bn1.num_batches_tracked

layer1.1.conv2.weight
synk

layer1.1.bn2.weight

layer1.1.bn2.bias

layer1.1.bn2.running_mean

layer1.1.bn2.running_var

layer1.1.bn2.num_batches_tracked

layer2.0.conv1.weight
synk

layer2.0.bn1.weight

layer2.0.bn1.bias

layer2.0.bn1.running_mean

layer2.0.bn1.running_var

layer2.0.bn1.num_batches_tracked

layer2.0.conv2.weight
synk

layer2.0.bn2.weight

lay

In [5]:
myresnet18_withbnlayer_wval = ResNet18(use_pretrained=True, transfer_learning = True,use_bn_layer = True,use_bn = True)

note that conv1_kernel_size is : 7
Start synking model with pretrained

conv1.weight
synk

bn1.weight
synk

bn1.bias
synk

bn1.running_mean
synk

bn1.running_var
synk

bn1.num_batches_tracked
synk

layer1.0.conv1.weight
synk

layer1.0.bn1.weight
synk

layer1.0.bn1.bias
synk

layer1.0.bn1.running_mean
synk

layer1.0.bn1.running_var
synk

layer1.0.bn1.num_batches_tracked
synk

layer1.0.conv2.weight
synk

layer1.0.bn2.weight
synk

layer1.0.bn2.bias
synk

layer1.0.bn2.running_mean
synk

layer1.0.bn2.running_var
synk

layer1.0.bn2.num_batches_tracked
synk

layer1.1.conv1.weight
synk

layer1.1.bn1.weight
synk

layer1.1.bn1.bias
synk

layer1.1.bn1.running_mean
synk

layer1.1.bn1.running_var
synk

layer1.1.bn1.num_batches_tracked
synk

layer1.1.conv2.weight
synk

layer1.1.bn2.weight
synk

layer1.1.bn2.bias
synk

layer1.1.bn2.running_mean
synk

layer1.1.bn2.running_var
synk

layer1.1.bn2.num_batches_tracked
synk

layer2.0.conv1.weight
synk

layer2.0.bn1.weight
synk

layer2.0.bn1.bias
synk

laye

In [12]:
import torch.nn as nn
import copy
for name,module in myresnet18_withbnlayer_wval.named_modules():
    if isinstance(module, nn.BatchNorm2d):
        print(name)
        print(module)
        print(module._parameters)

bn1
BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
OrderedDict([('weight', Parameter containing:
tensor([ 2.3487e-01,  2.6626e-01, -5.1096e-08,  5.1870e-01,  3.4404e-09,
         2.2239e-01,  4.2289e-01,  1.3153e-07,  2.5093e-01,  1.5152e-06,
         3.1687e-01,  2.5049e-01,  3.7893e-01,  1.0862e-05,  2.7526e-01,
         2.3674e-01,  2.4202e-01,  3.9531e-01,  4.6935e-01,  2.9090e-01,
         2.7268e-01,  2.7803e-01,  2.9069e-01,  2.0693e-01,  2.5899e-01,
         2.7871e-01,  2.9115e-01,  3.1601e-01,  3.8889e-01,  3.0411e-01,
         2.6776e-01,  2.1093e-01,  2.8708e-01,  3.3243e-01,  4.2673e-01,
         3.7326e-01,  7.4804e-08,  1.9068e-01,  1.4740e-08,  2.2303e-01,
         1.7908e-01,  2.4860e-01,  2.7400e-01,  2.5923e-01,  2.9420e-01,
         2.9924e-01,  2.2369e-01,  2.6280e-01,  2.2001e-08,  2.6610e-01,
         2.2089e-01,  2.8429e-01,  3.3072e-01,  2.2681e-01,  3.6538e-01,
         2.1230e-01,  2.3965e-01,  2.4950e-01,  5.2583e-01,  2.4825

In [6]:
myresnet18 = ResNet18(use_pretrained=True, transfer_learning = True,use_bn_layer = False,use_bn = False)

note that conv1_kernel_size is : 7
Start synking model with pretrained

conv1.weight
synk

bn1.weight

bn1.bias

layer1.0.conv1.weight
synk

layer1.0.bn1.weight

layer1.0.bn1.bias

layer1.0.conv2.weight
synk

layer1.0.bn2.weight

layer1.0.bn2.bias

layer1.1.conv1.weight
synk

layer1.1.bn1.weight

layer1.1.bn1.bias

layer1.1.conv2.weight
synk

layer1.1.bn2.weight

layer1.1.bn2.bias

layer2.0.conv1.weight
synk

layer2.0.bn1.weight

layer2.0.bn1.bias

layer2.0.conv2.weight
synk

layer2.0.bn2.weight

layer2.0.bn2.bias

layer2.0.downsample.0.weight
synk

layer2.0.downsample.1.weight

layer2.0.downsample.1.bias

layer2.1.conv1.weight
synk

layer2.1.bn1.weight

layer2.1.bn1.bias

layer2.1.conv2.weight
synk

layer2.1.bn2.weight

layer2.1.bn2.bias

layer3.0.conv1.weight
synk

layer3.0.bn1.weight

layer3.0.bn1.bias

layer3.0.conv2.weight
synk

layer3.0.bn2.weight

layer3.0.bn2.bias

layer3.0.downsample.0.weight
synk

layer3.0.downsample.1.weight

layer3.0.downsample.1.bias

layer3.1.conv1.weight

In [88]:
import torch.nn as nn
import copy
for name,module in myresnet18.named_modules():
    if isinstance(module, nn.GroupNorm):
        print(name)
        print(module)
        gn = getattr(myresnet18,name)
        print(gn)
        bn = nn.BatchNorm2d(gn.num_channels)
        print(bn)
        #print(myresnet18.name)
        (setattr(myresnet18, name, bn))
        myresnet18._modules[name] = nn.BatchNorm2d(module.num_channels)
        print(myresnet18._modules[name])

layer1.0.bn1
GroupNorm(2, 64, eps=1e-05, affine=True)
BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)


AttributeError: 'BatchNorm2d' object has no attribute 'num_channels'

In [87]:
isinstance(nn.BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), nn.GroupNorm)

False

In [81]:
dir(myresnet18)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_make_layer',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_version',
 'add_mod

In [80]:
for name,module in myresnet18.named_modules():
    if isinstance(module, nn.GroupNorm):
        print(name)

layer1.0.bn1
layer1.0.bn2
layer1.1.bn1
layer1.1.bn2
layer2.0.bn1
layer2.0.bn2
layer2.0.downsample.1
layer2.1.bn1
layer2.1.bn2
layer3.0.bn1
layer3.0.bn2
layer3.0.downsample.1
layer3.1.bn1
layer3.1.bn2
layer4.0.bn1
layer4.0.bn2
layer4.0.downsample.1
layer4.1.bn1
layer4.1.bn2


In [4]:
my_res_dict = myresnet18.state_dict()
res_dict = resnet18.state_dict()

In [5]:
print(my_res_dict.keys())

odict_keys(['conv1.weight', 'bn1.weight', 'bn1.bias', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.1.conv1.weight', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.conv2.weight', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer2.0.conv1.weight', 'layer2.0.bn1.weight', 'layer2.0.bn1.bias', 'layer2.0.conv2.weight', 'layer2.0.bn2.weight', 'layer2.0.bn2.bias', 'layer2.0.downsample.0.weight', 'layer2.0.downsample.1.weight', 'layer2.0.downsample.1.bias', 'layer2.1.conv1.weight', 'layer2.1.bn1.weight', 'layer2.1.bn1.bias', 'layer2.1.conv2.weight', 'layer2.1.bn2.weight', 'layer2.1.bn2.bias', 'layer3.0.conv1.weight', 'layer3.0.bn1.weight', 'layer3.0.bn1.bias', 'layer3.0.conv2.weight', 'layer3.0.bn2.weight', 'layer3.0.bn2.bias', 'layer3.0.downsample.0.weight', 'layer3.0.downsample.1.weight', 'layer3.0.downsample.1.bias', 'layer3.1.conv1.weight', 'layer3.1.bn1.weight', 'layer3.1.bn1.bias',

In [6]:
print(res_dict.keys())

odict_keys(['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.num_batches_tracked', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.num_batches_tracked', 'layer1.1.conv1.weight', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.bn1.running_mean', 'layer1.1.bn1.running_var', 'layer1.1.bn1.num_batches_tracked', 'layer1.1.conv2.weight', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer1.1.bn2.running_mean', 'layer1.1.bn2.running_var', 'layer1.1.bn2.num_batches_tracked', 'layer2.0.conv1.weight', 'layer2.0.bn1.weight', 'layer2.0.bn1.bias', 'layer2.0.bn1.running_mean', 'layer2.0.bn1.running_var', 'layer2.0.bn1.num_batches_tracked', 'layer2.0.conv2.weight', 'layer2.0.bn2.weight', 'layer2.0.bn2.bias', '

In [5]:
print(my_res_dict['conv1.weight'][0])

tensor([[[-1.0419e-02, -6.1356e-03, -1.8098e-03,  7.4841e-02,  5.6615e-02,
           1.7083e-02, -1.2694e-02],
         [ 1.1083e-02,  9.5276e-03, -1.0993e-01, -2.8050e-01, -2.7124e-01,
          -1.2907e-01,  3.7424e-03],
         [-6.9434e-03,  5.9089e-02,  2.9548e-01,  5.8720e-01,  5.1972e-01,
           2.5632e-01,  6.3573e-02],
         [ 3.0505e-02, -6.7018e-02, -2.9841e-01, -4.3868e-01, -2.7085e-01,
          -6.1282e-04,  5.7602e-02],
         [-2.7535e-02,  1.6045e-02,  7.2595e-02, -5.4102e-02, -3.3285e-01,
          -4.2058e-01, -2.5781e-01],
         [ 3.0613e-02,  4.0960e-02,  6.2850e-02,  2.3897e-01,  4.1384e-01,
           3.9359e-01,  1.6606e-01],
         [-1.3736e-02, -3.6746e-03, -2.4084e-02, -6.5877e-02, -1.5070e-01,
          -8.2230e-02, -5.7828e-03]],

        [[-1.1397e-02, -2.6619e-02, -3.4641e-02,  3.6812e-02,  3.2521e-02,
           6.6221e-04, -2.5743e-02],
         [ 4.5687e-02,  3.3603e-02, -1.0453e-01, -3.0885e-01, -3.1253e-01,
          -1.6051e-01, -1.2

In [6]:
print(res_dict['conv1.weight'][0])

tensor([[[-1.0419e-02, -6.1356e-03, -1.8098e-03,  7.4841e-02,  5.6615e-02,
           1.7083e-02, -1.2694e-02],
         [ 1.1083e-02,  9.5276e-03, -1.0993e-01, -2.8050e-01, -2.7124e-01,
          -1.2907e-01,  3.7424e-03],
         [-6.9434e-03,  5.9089e-02,  2.9548e-01,  5.8720e-01,  5.1972e-01,
           2.5632e-01,  6.3573e-02],
         [ 3.0505e-02, -6.7018e-02, -2.9841e-01, -4.3868e-01, -2.7085e-01,
          -6.1282e-04,  5.7602e-02],
         [-2.7535e-02,  1.6045e-02,  7.2595e-02, -5.4102e-02, -3.3285e-01,
          -4.2058e-01, -2.5781e-01],
         [ 3.0613e-02,  4.0960e-02,  6.2850e-02,  2.3897e-01,  4.1384e-01,
           3.9359e-01,  1.6606e-01],
         [-1.3736e-02, -3.6746e-03, -2.4084e-02, -6.5877e-02, -1.5070e-01,
          -8.2230e-02, -5.7828e-03]],

        [[-1.1397e-02, -2.6619e-02, -3.4641e-02,  3.6812e-02,  3.2521e-02,
           6.6221e-04, -2.5743e-02],
         [ 4.5687e-02,  3.3603e-02, -1.0453e-01, -3.0885e-01, -3.1253e-01,
          -1.6051e-01, -1.2

In [9]:
my_res_dict = myresnet18.state_dict()
res_dict = resnet18.state_dict()
except_names = ['bn','downsample.1']
for name in my_res_dict.keys():
    print()
    print(name)
    skip = False
    if except_names!=[]:
        for except_name in except_names:
            if except_name in name:
                skip = True
                continue
    if not skip:
        try:
            
            pre_par = res_dict[name]
            if my_res_dict[name].shape == pre_par.shape:
                my_res_dict[name] = pre_par
                print("sink")
            else:
                print("Shape is not same")
                print('my_shape:', my_res_dict[name].shape)
                print('pretrained shape:', pre_par.shape)
            
        except:
            
            pass

        


conv1.weight
sink

bn1.weight

bn1.bias

layer1.0.conv1.weight
sink

layer1.0.bn1.weight

layer1.0.bn1.bias

layer1.0.conv2.weight
sink

layer1.0.bn2.weight

layer1.0.bn2.bias

layer1.1.conv1.weight
sink

layer1.1.bn1.weight

layer1.1.bn1.bias

layer1.1.conv2.weight
sink

layer1.1.bn2.weight

layer1.1.bn2.bias

layer2.0.conv1.weight
sink

layer2.0.bn1.weight

layer2.0.bn1.bias

layer2.0.conv2.weight
sink

layer2.0.bn2.weight

layer2.0.bn2.bias

layer2.0.downsample.0.weight
sink

layer2.0.downsample.1.weight

layer2.0.downsample.1.bias

layer2.1.conv1.weight
sink

layer2.1.bn1.weight

layer2.1.bn1.bias

layer2.1.conv2.weight
sink

layer2.1.bn2.weight

layer2.1.bn2.bias

layer3.0.conv1.weight
sink

layer3.0.bn1.weight

layer3.0.bn1.bias

layer3.0.conv2.weight
sink

layer3.0.bn2.weight

layer3.0.bn2.bias

layer3.0.downsample.0.weight
sink

layer3.0.downsample.1.weight

layer3.0.downsample.1.bias

layer3.1.conv1.weight
sink

layer3.1.bn1.weight

layer3.1.bn1.bias

layer3.1.conv2.weight
si

In [10]:
resnet18.fc.bias.shape

torch.Size([1000])

In [11]:
myresnet18.load_state_dict(my_res_dict)

<All keys matched successfully>

In [7]:
print(myresnet18.conv1.weight[0])

tensor([[[-1.0419e-02, -6.1356e-03, -1.8098e-03,  7.4841e-02,  5.6615e-02,
           1.7083e-02, -1.2694e-02],
         [ 1.1083e-02,  9.5276e-03, -1.0993e-01, -2.8050e-01, -2.7124e-01,
          -1.2907e-01,  3.7424e-03],
         [-6.9434e-03,  5.9089e-02,  2.9548e-01,  5.8720e-01,  5.1972e-01,
           2.5632e-01,  6.3573e-02],
         [ 3.0505e-02, -6.7018e-02, -2.9841e-01, -4.3868e-01, -2.7085e-01,
          -6.1282e-04,  5.7602e-02],
         [-2.7535e-02,  1.6045e-02,  7.2595e-02, -5.4102e-02, -3.3285e-01,
          -4.2058e-01, -2.5781e-01],
         [ 3.0613e-02,  4.0960e-02,  6.2850e-02,  2.3897e-01,  4.1384e-01,
           3.9359e-01,  1.6606e-01],
         [-1.3736e-02, -3.6746e-03, -2.4084e-02, -6.5877e-02, -1.5070e-01,
          -8.2230e-02, -5.7828e-03]],

        [[-1.1397e-02, -2.6619e-02, -3.4641e-02,  3.6812e-02,  3.2521e-02,
           6.6221e-04, -2.5743e-02],
         [ 4.5687e-02,  3.3603e-02, -1.0453e-01, -3.0885e-01, -3.1253e-01,
          -1.6051e-01, -1.2

In [8]:
print(myresnet18.bn1.weight)

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)


In [9]:
print(resnet18.bn1.weight)

Parameter containing:
tensor([ 2.3487e-01,  2.6626e-01, -5.1096e-08,  5.1870e-01,  3.4404e-09,
         2.2239e-01,  4.2289e-01,  1.3153e-07,  2.5093e-01,  1.5152e-06,
         3.1687e-01,  2.5049e-01,  3.7893e-01,  1.0862e-05,  2.7526e-01,
         2.3674e-01,  2.4202e-01,  3.9531e-01,  4.6935e-01,  2.9090e-01,
         2.7268e-01,  2.7803e-01,  2.9069e-01,  2.0693e-01,  2.5899e-01,
         2.7871e-01,  2.9115e-01,  3.1601e-01,  3.8889e-01,  3.0411e-01,
         2.6776e-01,  2.1093e-01,  2.8708e-01,  3.3243e-01,  4.2673e-01,
         3.7326e-01,  7.4804e-08,  1.9068e-01,  1.4740e-08,  2.2303e-01,
         1.7908e-01,  2.4860e-01,  2.7400e-01,  2.5923e-01,  2.9420e-01,
         2.9924e-01,  2.2369e-01,  2.6280e-01,  2.2001e-08,  2.6610e-01,
         2.2089e-01,  2.8429e-01,  3.3072e-01,  2.2681e-01,  3.6538e-01,
         2.1230e-01,  2.3965e-01,  2.4950e-01,  5.2583e-01,  2.4825e-01,
         2.9565e-01,  2.5878e-01,  4.8326e-01,  2.6670e-01],
       requires_grad=True)


In [10]:
print(myresnet18.state_dict()['layer2.0.downsample.1.weight'])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])


In [11]:
print(resnet18.state_dict()['layer2.0.downsample.1.weight'])

tensor([ 0.3334,  0.0581,  0.0715,  0.3442,  0.1756,  0.1509,  0.1568,  0.3100,
         0.1927,  0.1516,  0.3044,  0.2238,  0.3706,  0.1739,  0.3051,  0.2610,
         0.1575,  0.2015,  0.2933,  0.1010,  0.5871,  0.0676,  0.2499,  0.0929,
         0.2443,  0.0495,  0.2449,  0.2750,  0.3071,  0.3025,  0.1818,  0.0688,
         0.2223,  0.3766,  0.4661,  0.3284,  0.1035,  0.3400,  0.2325,  0.1514,
         0.1753,  0.2269,  0.2606,  0.1831,  0.2894,  0.2590,  0.2208,  0.1399,
         0.0643,  0.2833,  0.3451,  0.2017,  0.0696,  0.2722,  0.1127,  0.2917,
         0.2358,  0.2703,  0.0911,  0.2591,  0.1302,  0.2261,  0.1967,  0.0539,
         0.0697,  0.0524,  0.1050,  0.0861,  0.1173,  0.0957,  0.1862,  0.1642,
         0.1336,  0.1065,  0.1312,  0.0888,  0.0793,  0.0475,  0.3049,  0.2325,
         0.2908,  0.1292,  0.0778,  0.2263,  0.2379,  0.3405,  0.0914,  0.1936,
         0.1223,  0.1400,  0.2953,  0.2360,  0.1681,  0.1338,  0.2666,  0.1495,
         0.0761,  0.1674,  0.1784,  0.17

In [ ]:
for a,b in my_res_dict:
    print(a,b)

In [ ]:
myresnet18.load_state_dict(my_res_dict)

In [ ]:
for name,par in resnet18.named_parameters():
    print(name)


In [ ]:
for name,par in resnet18.named_parameters():
    print(name)
    print(par.requires_grad)

In [ ]:
for name,par in resnet18.named_parameters():
    if "fc" in name:
        print("Freeze classifier at the beginning")
        print(name)
        par.requires_grad=False

In [ ]:
for name,par in resnet18.named_parameters():
    print(name)
    print(par.requires_grad)

In [ ]:
from resnet import ResNet18

In [ ]:
a=ResNet18()


In [ ]:
for name,par in a.named_parameters():
    print(name)
    print(par.requires_grad)

In [ ]:
for name,par in a.named_parameters():
    if 'linear' in name:
        par.requires_grad=False

In [ ]:
for name,par in a.named_parameters():
    print(name)
    print(par.requires_grad)

In [ ]:
for aa in (a.children()):
    print(aa)

In [ ]:
list(a.children())[:-1]

In [ ]:
import torch
import torch.nn as nn
from torchvision import models

In [ ]:
class feature_extractor(nn.Module):
            def __init__(self,model,classifier_index=-1):
                super(feature_extractor, self).__init__()
                self.features = nn.Sequential(
                    # stop at conv4
                    *list(model.children())[:classifier_index]
                )
            def forward(self, x):
                x = self.features(x)
                return x

model = feature_extractor(a)

In [ ]:
print(model)

In [ ]:
list(a.parameters())[0]

In [ ]:
list(model.parameters())[0]

In [ ]:
for asdf in model.parameters():
    asdf.requires_grad=False

In [ ]:
list(model.parameters())[0]

In [1]:
from resnet_wDiscriminator import ResNet18

In [2]:
a = ResNet18()
aa = a.state_dict()

In [3]:
for name,par in a.named_parameters():
    print(name)
    print(par.requires_grad)

conv1.weight
True
bn1.weight
True
bn1.bias
True
layer1.0.conv1.weight
True
layer1.0.bn1.weight
True
layer1.0.bn1.bias
True
layer1.0.conv2.weight
True
layer1.0.bn2.weight
True
layer1.0.bn2.bias
True
layer1.1.conv1.weight
True
layer1.1.bn1.weight
True
layer1.1.bn1.bias
True
layer1.1.conv2.weight
True
layer1.1.bn2.weight
True
layer1.1.bn2.bias
True
layer2.0.conv1.weight
True
layer2.0.bn1.weight
True
layer2.0.bn1.bias
True
layer2.0.conv2.weight
True
layer2.0.bn2.weight
True
layer2.0.bn2.bias
True
layer2.0.downsample.0.weight
True
layer2.0.downsample.1.weight
True
layer2.0.downsample.1.bias
True
layer2.1.conv1.weight
True
layer2.1.bn1.weight
True
layer2.1.bn1.bias
True
layer2.1.conv2.weight
True
layer2.1.bn2.weight
True
layer2.1.bn2.bias
True
layer3.0.conv1.weight
True
layer3.0.bn1.weight
True
layer3.0.bn1.bias
True
layer3.0.conv2.weight
True
layer3.0.bn2.weight
True
layer3.0.bn2.bias
True
layer3.0.downsample.0.weight
True
layer3.0.downsample.1.weight
True
layer3.0.downsample.1.bias
True
la

In [4]:
a.freezeDis_unfreezeElse()

In [5]:
for name,par in a.named_parameters():
    print(name)
    print(par.requires_grad)

conv1.weight
True
bn1.weight
True
bn1.bias
True
layer1.0.conv1.weight
True
layer1.0.bn1.weight
True
layer1.0.bn1.bias
True
layer1.0.conv2.weight
True
layer1.0.bn2.weight
True
layer1.0.bn2.bias
True
layer1.1.conv1.weight
True
layer1.1.bn1.weight
True
layer1.1.bn1.bias
True
layer1.1.conv2.weight
True
layer1.1.bn2.weight
True
layer1.1.bn2.bias
True
layer2.0.conv1.weight
True
layer2.0.bn1.weight
True
layer2.0.bn1.bias
True
layer2.0.conv2.weight
True
layer2.0.bn2.weight
True
layer2.0.bn2.bias
True
layer2.0.downsample.0.weight
True
layer2.0.downsample.1.weight
True
layer2.0.downsample.1.bias
True
layer2.1.conv1.weight
True
layer2.1.bn1.weight
True
layer2.1.bn1.bias
True
layer2.1.conv2.weight
True
layer2.1.bn2.weight
True
layer2.1.bn2.bias
True
layer3.0.conv1.weight
True
layer3.0.bn1.weight
True
layer3.0.bn1.bias
True
layer3.0.conv2.weight
True
layer3.0.bn2.weight
True
layer3.0.bn2.bias
True
layer3.0.downsample.0.weight
True
layer3.0.downsample.1.weight
True
layer3.0.downsample.1.bias
True
la

In [6]:
a.unfreezeDis_freezeElse()

In [7]:
for name,par in a.named_parameters():
    print(name)
    print(par.requires_grad)

conv1.weight
False
bn1.weight
False
bn1.bias
False
layer1.0.conv1.weight
False
layer1.0.bn1.weight
False
layer1.0.bn1.bias
False
layer1.0.conv2.weight
False
layer1.0.bn2.weight
False
layer1.0.bn2.bias
False
layer1.1.conv1.weight
False
layer1.1.bn1.weight
False
layer1.1.bn1.bias
False
layer1.1.conv2.weight
False
layer1.1.bn2.weight
False
layer1.1.bn2.bias
False
layer2.0.conv1.weight
False
layer2.0.bn1.weight
False
layer2.0.bn1.bias
False
layer2.0.conv2.weight
False
layer2.0.bn2.weight
False
layer2.0.bn2.bias
False
layer2.0.downsample.0.weight
False
layer2.0.downsample.1.weight
False
layer2.0.downsample.1.bias
False
layer2.1.conv1.weight
False
layer2.1.bn1.weight
False
layer2.1.bn1.bias
False
layer2.1.conv2.weight
False
layer2.1.bn2.weight
False
layer2.1.bn2.bias
False
layer3.0.conv1.weight
False
layer3.0.bn1.weight
False
layer3.0.bn1.bias
False
layer3.0.conv2.weight
False
layer3.0.bn2.weight
False
layer3.0.bn2.bias
False
layer3.0.downsample.0.weight
False
layer3.0.downsample.1.weight
Fa